version: '3.8'
services:
  color-analyzer-api:
    build: .
    ports:
      - "3001:3001"
    container_name: color-tools-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      - /etc/localtime:/etc/localtime:ro
    security_opt:
      - seccomp:unconfined
    networks:
      - default